### ISSUE TITLE
vfs2.FileSystemException on unzipping grails distribution

### ISSUE THREAD

**Issue by arturashyrov** [ConnorWGarvey/gradle-grails-wrapper#1] opened 2012-04-11 14:56 UTC
Hi. I'm getting exception when trying to run 'gradle grails-run-app' command on my project.
My environment:
windows7
jdk7
Gradle - Version 1.0-milestone-9

Here is my gradle.build file:

apply plugin: 'grails'

buildscript {
  repositories {
    mavenCentral()
    maven { url 'http://connorwgarvey.github.com/gradle-grails-wrapper/repo/' }
  }
  dependencies {
    classpath 'com.connorgarvey.gradle:gradle-grails-wrapper:0.3'
  }
}

grails {
  version '2.0.3' 
}

Here is stacktrace that i get:

17:09:42.462 [DEBUG] [org.apache.commons.vfs2.cache.SoftRefFilesCache] putFile: file:///C:/Users/ruel/.gradlegrails/tmp/grails-2.0.3/dist/grails-crud-2.0.3.jar
17:09:42.478 [DEBUG] [org.apache.commons.vfs2.cache.SoftRefFilesCache] putFile: file:///C:/Users/ruel/.gradlegrails/tmp/grails-2.0.3/dist/grails-plugin-servlets-2.0.3
.jar
17:09:42.492 [DEBUG] [org.apache.commons.vfs2.cache.SoftRefFilesCache] putFile: file:///C:/Users/ruel/.gradlegrails/tmp/grails-2.0.3/dist/grails-scripts-2.0.3.jar
17:09:42.543 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEv
entRenderer@6f824c0c, org.gradle.logging.internal.slf4j.Slf4jLoggingConfigurer@534ee105, org.gradle.logging.internal.JavaUtilLoggingConfigurer@5f9739fd]
17:09:42.552 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':install-grails'
17:09:42.566 [ERROR] [org.gradle.BuildExceptionReporter]
17:09:42.576 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:09:42.586 [ERROR] [org.gradle.BuildExceptionReporter]
17:09:42.594 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
17:09:42.601 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':install-grails'.
17:09:42.610 [ERROR] [org.gradle.BuildExceptionReporter] > org.apache.commons.vfs2.FileSystemException: Could not find file with URI "/Users/ruel/.gradlegrails/grails
/2.0.3\bin" because it is a relative path, and no base URI was provided.
17:09:42.619 [ERROR] [org.gradle.BuildExceptionReporter]
17:09:42.626 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
17:09:42.634 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':install-grails'.
17:09:42.642 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTas
kExecuter.java:68)
17:09:42.649 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecut
er.java:46)
17:09:42.657 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnal
ysisTaskExecuter.java:34)
17:09:42.663 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter$1.run(CacheLockHandlingTaskEx
ecuter.java:34)
17:09:42.670 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess$2.create(DefaultCacheAccess.java:200)
17:09:42.677 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:172)
17:09:42.685 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:198)
17:09:42.692 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDir
ectoryStore.java:111)
17:09:42.699 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.longRunningOperation(De
faultTaskArtifactStateCacheAccess.java:83)
17:09:42.705 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter.execute(CacheLockHandlingTask
Executer.java:32)
17:09:42.712 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.j
ava:55)
17:09:42.719 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:
57)
17:09:42.726 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFil
esTaskExecuter.java:41)
17:09:42.733 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActions
Executer.java:51)
17:09:42.741 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:
52)
17:09:42.749 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTask
Executer.java:42)
17:09:42.756 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:247)
17:09:42.763 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultTaskGraphExecuter.executeTask(DefaultTaskGraphExecuter.java:192)
17:09:42.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultTaskGraphExecuter.doExecute(DefaultTaskGraphExecuter.java:177)
17:09:42.777 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:83)
17:09:42.785 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:36)
17:09:42.792 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
17:09:42.800 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
17:09:42.806 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
17:09:42.813 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter$1.run(TaskCacheLockHandl
ingBuildExecuter.java:31)
17:09:42.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess$1.create(DefaultCacheAccess.java:111)
17:09:42.828 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:126)
17:09:42.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:109)
17:09:42.842 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.
java:103)
17:09:42.850 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArt
ifactStateCacheAccess.java:79)
17:09:42.857 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.TaskCacheLockHandlingBuildExecuter.execute(TaskCacheLockHan
dlingBuildExecuter.java:29)
17:09:42.865 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
17:09:42.872 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
17:09:42.879 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
17:09:42.887 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
17:09:42.894 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
17:09:42.902 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
17:09:42.909 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
17:09:42.917 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:110)
17:09:42.924 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:78)
17:09:42.931 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:42)
17:09:42.939 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.execute(RunBuildAction.java:28)
17:09:42.946 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:32)
17:09:42.953 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ExceptionReportingAction.execute(ExceptionReportingAction.java:21)
17:09:42.961 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory
.java:302)
17:09:42.968 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory
.java:286)
17:09:42.976 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:48)
17:09:42.983 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.EntryPoint$1.execute(EntryPoint.java:53)
17:09:42.991 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.EntryPoint$1.execute(EntryPoint.java:51)
17:09:42.998 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.Execution.execute(Execution.java:28)
17:09:43.006 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.EntryPoint.run(EntryPoint.java:39)
17:09:43.013 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:39)
17:09:43.021 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:51)
17:09:43.028 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:33)
17:09:43.035 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
17:09:43.043 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: org.apache.commons.vfs2.FileSystemExceptio
n: Could not find file with URI "/Users/ruel/.gradlegrails/grails/2.0.3\bin" because it is a relative path, and no base URI was provided.
17:09:43.050 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:452)
17:09:43.058 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:436)
17:09:43.065 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTas
kExecuter.java:60)
17:09:43.073 [ERROR] [org.gradle.BuildExceptionReporter]        ... 54 more
17:09:43.080 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.apache.commons.vfs2.FileSystemException: Could not find file with URI "/Users/ruel/.gradlegrai
ls/grails/2.0.3\bin" because it is a relative path, and no base URI was provided.
17:09:43.087 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:719
)
17:09:43.095 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649
)
17:09:43.103 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:605
)
17:09:43.110 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.vfs2.FileSystemManager$resolveFile.call(Unknown Source)
17:09:43.118 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin.unzipGrails(GrailsPlugin.groovy:193)
17:09:43.125 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin.this$2$unzipGrails(GrailsPlugin.groovy)
17:09:43.133 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin$this$2$unzipGrails.callCurrent(Unknown Source)
17:09:43.141 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin.download(GrailsPlugin.groovy:152)
17:09:43.148 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin.this$2$download(GrailsPlugin.groovy)
17:09:43.156 [ERROR] [org.gradle.BuildExceptionReporter]        at com.connorgarvey.gradlegrails.GrailsPlugin$_apply_closure3.doCall(GrailsPlugin.groovy:61)
17:09:43.163 [ERROR] [org.gradle.BuildExceptionReporter]        ... 57 more
17:09:43.171 [ERROR] [org.gradle.BuildExceptionReporter]
17:09:43.178 [LIFECYCLE] [org.gradle.BuildResultLogger]
17:09:43.185 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
17:09:43.194 [LIFECYCLE] [org.gradle.BuildResultLogger]
17:09:43.201 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 2 mins 25.429 secs

**Comment by ConnorWGarvey** [comment] 2012-04-13 18:11
Thank you.  It's most likely a problem with how the path is constructed in Windows.  I'll give it a look as soon as I can.

**Comment by ConnorWGarvey** [comment] 2012-04-19 17:55
Will be released in 0.4.

**Closed as completed by ConnorWGarvey** 2012-04-19 17:55 UTC

**Comment by ConnorWGarvey** [comment] 2012-04-21 03:33
This was caused by a problem with Apache VFS on Windows.  0.4.1 fixed the problem for me and is now synced to Maven Central.  Please let me know if you have any more problems.

**Comment by arturashyrov** [comment] 2012-04-22 14:19
Ok. Thanks. Just tried 0.4.1 everything works fine
